### PR TITLE
Add CLI options for screen and CRTC selection

### PR DESCRIPTION
**Pull request by faf0**
- Add options for screen and CRTC selection.
- Address https://github.com/faf0/sct/issues/25 .

### CODE REVIEW

**Comment by faf0** [comment]
@zikzik @zvezdochiot feel free to review

**Comment by zvezdochiot** [comment]
Hi @faf0 .

Maybe replace?:
https://github.com/faf0/sct/blob/fb88ee15a5838d34a2a4826e099dee1a57649dce/xsct.c#L246
to
https://github.com/faf0/sct/blob/fb88ee15a5838d34a2a4826e099dee1a57649dce/xsct.c#L266

PS: Perhaps someone will need an assessment of a particular screen.

**Comment by faf0** [comment]
@zvezdochiot good idea. updated in https://github.com/faf0/sct/pull/28/commits/1191719eeffa32e292aaaff005e5cac6968d0bf9 .

**Comment by zvezdochiot** [comment]
Hi @faf0 

Typo?
https://github.com/faf0/sct/blob/1191719eeffa32e292aaaff005e5cac6968d0bf9/xsct.c#L20
and
https://github.com/faf0/sct/blob/1191719eeffa32e292aaaff005e5cac6968d0bf9/xsct.1#L4-L9
:question: [screen_index] [crtc_index]?

---

Maybe?
https://github.com/faf0/sct/blob/1191719eeffa32e292aaaff005e5cac6968d0bf9/xsct.c#L27-L28
to
```c
           "\t-s, --screen N \t xsct will only select screen specified by given zero-based index\n"
           "\t-c, --crtc N \t xsct will only select CRTC specified by given zero-based index\n", pname);
```
and
https://github.com/faf0/sct/blob/1191719eeffa32e292aaaff005e5cac6968d0bf9/xsct.1#L25-L30
to
```man
.TP
.B -s, --screen N
Zero-based index of screen to use.
.TP
.B -c, --crtc N
Zero-based index of CRTC to use.
```

**Comment by zvezdochiot** [comment]
Hi @faf0 .

Maybe?
https://github.com/faf0/sct/blob/1191719eeffa32e292aaaff005e5cac6968d0bf9/xsct.c#L27-L28
to
```c
           "\t-s, --screen (value)\t xsct will only select screen specified by given zero-based index\n"
           "\t-c, --crtc (value) \t xsct will only select CRTC specified by given zero-based index\n", pname);
```
and
https://github.com/faf0/sct/blob/1191719eeffa32e292aaaff005e5cac6968d0bf9/xsct.1#L25-L30
to
```man
.TP
.B -s, --screen (value)
Zero-based index of screen to use.
.TP
.B -c, --crtc (value)
Zero-based index of CRTC to use.
```

**Comment by faf0** [comment]
Thanks, @zvezdochiot ! I updated the documentation in https://github.com/faf0/sct/pull/28/commits/423aefc86a8b445640b1c34d0142e514057c3cb3 .

**Comment by zvezdochiot** [comment]
Hi @faf0 .

:+1: Good work!

**Pull request merged**
